/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CardButton {
    'type': string;
    'variation': string;
  }
  interface DataCard {
    /**
    * The card description
    */
    'desc': string;
    /**
    * The card title
    */
    'heading': string;
    /**
    * The card image
    */
    'isReversed': boolean;
    /**
    * The card image
    */
    'src': string;
  }
}

declare global {


  interface HTMLCardButtonElement extends Components.CardButton, HTMLStencilElement {}
  var HTMLCardButtonElement: {
    prototype: HTMLCardButtonElement;
    new (): HTMLCardButtonElement;
  };

  interface HTMLDataCardElement extends Components.DataCard, HTMLStencilElement {}
  var HTMLDataCardElement: {
    prototype: HTMLDataCardElement;
    new (): HTMLDataCardElement;
  };
  interface HTMLElementTagNameMap {
    'card-button': HTMLCardButtonElement;
    'data-card': HTMLDataCardElement;
  }
}

declare namespace LocalJSX {
  interface CardButton {
    'type'?: string;
    'variation'?: string;
  }
  interface DataCard {
    /**
    * The card description
    */
    'desc'?: string;
    /**
    * The card title
    */
    'heading'?: string;
    /**
    * The card image
    */
    'isReversed'?: boolean;
    /**
    * The card image
    */
    'src'?: string;
  }

  interface IntrinsicElements {
    'card-button': CardButton;
    'data-card': DataCard;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'card-button': LocalJSX.CardButton & JSXBase.HTMLAttributes<HTMLCardButtonElement>;
      'data-card': LocalJSX.DataCard & JSXBase.HTMLAttributes<HTMLDataCardElement>;
    }
  }
}


